FROM node:22-alpine AS builder

#set working directory
WORKDIR /app

# copy dependencies
COPY app/package.json app/package-lock.json ./

RUN npm ci

# install dependencies first to leverage docker's layer caching
RUN npm install

COPY app/vite.config.js ./
COPY app/src ./src
COPY app/public ./public
COPY app/index.html ./
RUN npm run build

FROM nginx:alpine AS production

# set cd of prod
WORKDIR /app

# copy build from dev stage into the nginx serve path 
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]



