FROM node:22-alpine AS builder

WORKDIR /app


COPY app/package.json app/package-lock.json ./

RUN npm ci


RUN npm install

COPY app/vite.config.js ./
COPY app/src ./src
COPY app/public ./public
COPY app/index.html ./
RUN npm run build

FROM nginx:alpine AS production

WORKDIR /app

 
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]



